[build.environment]
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-legacy-deps"
  DART_SASS_VERSION = "1.92.1"
  GO_VERSION = "1.25.1"
  HUGO_VERSION = "0.150.0"
  NODE_VERSION = "22.18.0"
  TZ = "Europe/London"

[build]
publish = "public"
command = """\
  curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  tar -C "${HOME}/.local" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  rm "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  export PATH="${HOME}/.local/dart-sass:${PATH}" && \
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}" -s site -d ../dist \
  sed -e 's/mediascreen/media screen/g' -i main.min.*.css \
  """

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true